name: Intatera
favicon: null
layout_spectrum: 0.6866583449300379
typography_spectrum: 0.3040187982842326
title: Intatera by Cheryl Marlene
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a0000'
    - '#140202'
    - '#b0000a'
    - '#86111a'
    - '#b1212b'
  brandStrength: 1
  lightness: 0.7392778329085559
  saturation: 0.5
  rhythmicContrast: 0.7420548722147942
purpose: []
